### ISSUE TITLE
Locator Map google doc seems to be private

### ISSUE THREAD

**Issue by brentajones** [nprapps/dailygraphics#116]
When I run `fab add_map:{slug}` I get:

```
[localhost] local: cp -r graphic_templates/_base /Users/brentjones/graphics/test
[localhost] local: cp -r graphic_templates/locator_map/* /Users/brentjones/graphics/test
Creating spreadsheet...
Error creating spreadsheet (status code 404) with message Not Found
Traceback (most recent call last):
  File "/Users/brentjones/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/brentjones/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/brentjones/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/brentjones/dailygraphics/fabfile/__init__.py", line 290, in add_locator_map
    _add_graphic(slug, 'locator_map')
  File "/Users/brentjones/dailygraphics/fabfile/__init__.py", line 200, in _add_graphic
    download_copy(slug)
  File "/Users/brentjones/dailygraphics/fabfile/__init__.py", line 157, in download_copy
    get_document(graphic_config.COPY_GOOGLE_DOC_KEY, copy_path)
  File "/Users/brentjones/dailygraphics/oauth.py", line 123, in get_document
    raise KeyError("Error! Google returned a %s error" % response.status)
KeyError: 'Error! Google returned a 403 error'
```

If I manually visit the Google Doc in the graphic_config.py (https://docs.google.com/spreadsheets/d/1FwRh41h458JmMsT6sv7_kLrV_G_jtVdwoUw6tPJ4-90/edit#gid=0) I get an "Access Denied: You need permission" screen.

Thanks for these recent updates; they're great.

**Comment by dannydb** [comment]
Give it another try and let me know how it goes!

**Comment by brentajones** [comment]
Bingo. Thank you.
