### ISSUE TITLE
Google API connection stalls/breaks on Comcast

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#287]
It's entirely possible that this is just me, my computer and/or my glitchy home wifi, but noting it here for future reference.

When I open graphics in the dailygraphics rig with `refresh=1` in the URL, it will hang for minutes at a time. Sometimes it will eventually load. Sometimes, if I restart gunicorn and reload the page, it'll eventually load. Sometimes I get an authomatic `fetch` error.

```
Traceback (most recent call last):
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/AHurt/src/dailygraphics/oauth.py", line 86, in decorated_function
    return f(*args, **kwargs)
  File "/Users/AHurt/src/dailygraphics/graphic.py", line 54, in _graphics_detail
    oauth.get_document(graphic_config.COPY_GOOGLE_DOC_KEY, copy_path)
  File "/Users/AHurt/src/dailygraphics/oauth.py", line 129, in get_document
    response = app_config.authomatic.access(credentials, url)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/authomatic/core.py", line 1404, in access
    content_parser=content_parser)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/authomatic/providers/__init__.py", line 762, in access
    content_parser=content_parser)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/authomatic/providers/__init__.py", line 396, in _fetch
    url=request_path)
FetchError: Could not connect!
```

It sucks on my home Comcast connection, but works fine in the office and at Starbucks.

**Comment by alykat** [comment]
I'll add that it's not related to https://github.com/nprapps/dailygraphics/issues/254. I'm not on VPN.
