### ISSUE TITLE
Error when deploying a graphic w/o graphic_config.py

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#95]
```
(dailygraphics)ahurt-npr:dailygraphics AHurt$ fab staging deploy:map-discrimination-geo
map-discrimination-geo/graphic_config.py does not exist.
Traceback (most recent call last):
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/main.py", line 717, in main
    *args, **kwargs
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 332, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/AHurt/src/dailygraphics/fabfile/__init__.py", line 147, in deploy
    update_copy(slug)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 109, in __call__
    return self.run(*args, **kwargs)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/fabric/tasks.py", line 112, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/AHurt/src/dailygraphics/fabfile/__init__.py", line 201, in update_copy
    download_copy(slug)
  File "/Users/AHurt/src/dailygraphics/fabfile/__init__.py", line 186, in download_copy
    graphic_config = _graphic_config(slug)
  File "/Users/AHurt/src/dailygraphics/fabfile/__init__.py", line 37, in _graphic_config
    graphic_config = imp.load_source('graphic_config', '%s/graphic_config.py' % graphic_path)
IOError: [Errno 2] No such file or directory
```

**Comment by onyxfish** [comment]
Will fix now
